version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean install 
  post_build:
    commands:
      - echo "Uploading WAR to S3..."
      - aws s3 cp /root/.m2/repository/com/example/maven-project/webapp/1.0-SNAPSHOT/webapp-1.0-SNAPSHOT.war s3://mydemobucket08062025/webapp.war

artifacts:
  files:
    - /root/.m2/repository/com/example/maven-project/webapp/1.0-SNAPSHOT/webapp-1.0-SNAPSHOT.war
  discard-paths: yes
